---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
    - ["forwarded_port", {guest: 443, host: 8443}]
  customize:
    cpus: 2
    memory: 8096

provisioner:
  name: chef_zero

platforms:
  - name: chef/centos-7.1

suites:
  - name: host
    run_list:
      - recipe[test-atomic::default]
    attributes:
